---
title: "eds212-day4-session2"
format: html
editor: visual
execute: 
  warning: FALSE
---

## Creating Q on own

```{r}
library(GGally)
library(skimr)
library(palmerpenguins)
library(tidyverse)
```

## Basic Data Exploration

-   names: get variable names

-   dim: get data dim

-   head: get first n lines (6 by default)

-   tail: get last n lines (6 by default)

-   summary: get basic summary stats

```{r}
names(penguins)
```

```{r}
#If you do view in data chunk it will try to show in document so do not view data set in chunk to run so do view() in console
#view(penguins)

```

```{r}
#Will show you missing values, and how many variables there are. Informative when forming your own data set. It doesnt show relationships however
summary(penguins)
```

```{r}
#Skim gives quite a bit of information about different variables
skim(penguins)
```

```{r}
ggpairs(penguins)

```

## Making some more exploratory charts in ggplot2

Histogram

```{r}
#Based on constant, put that out of aes- note "fill"
ggplot(data = penguins, aes(x = flipper_length_mm)) +
  geom_histogram(aes(fill = species)) +
  theme_minimal()

```

```{r}
#Creating a box plot of bill lnegth vs species 
ggplot(data = penguins, aes(x = species, y = bill_length_mm)) +
  geom_boxplot(fill = "yellow", aes(color = island)) + 
  geom_jitter() + 
  theme_light()
```
